version: '3.8'
services:
  api:
    container_name: "blackonline_api"
    image: blackonline_api:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://blackonline_db:3306/blackonline_db
      - DATABASE_USERNAME=on
      - DATABASE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: blackonline_db
    environment:
      MYSQL_DATABASE: blackonline_db
      MYSQL_USER: on
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: